MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVillaAPI.Models;
using MagicVilla_Web.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using MagicVilla_Web.Models.VM;
using Microsoft.AspNetCore.Mvc.Rendering;
using MagicVillaAPI.Models.Dto;
using System.Text;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IHttpClientFactory _httpClient;
        private readonly IConfiguration _configuration;
        private readonly string villaUrl;
        private IMapper _mapper;

        public VillaNumberController(IHttpClientFactory httpClient, IConfiguration configuration, IMapper mapper)
        {
            _httpClient = httpClient;
            _configuration = configuration;
            villaUrl = _configuration.GetValue<string>("ServiceUrls:VillaAPI");
            _mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaNumberAPI");
            message.Method = HttpMethod.Get;

            HttpResponseMessage httpResponse = await client.SendAsync(message);

            var apiContent = await httpResponse.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<APIResponse>(apiContent);
            var villaNumberList = JsonConvert.DeserializeObject<List<Models.Dto.VillaNumberDTO>>(data.Result.ToString());
            return View(villaNumberList);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaAPI");
            message.Method = HttpMethod.Get;

            HttpResponseMessage httpResponse = await client.SendAsync(message);

            var apiContent = await httpResponse.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<APIResponse>(apiContent);
            var villaList = JsonConvert.DeserializeObject<List<Models.Dto.VillaDTO>>(data.Result.ToString());

            VillaNumberCreateVM villaNumberCreateVM = new VillaNumberCreateVM();
            villaNumberCreateVM.VillaList = villaList.Select(x => new SelectListItem
            {
                Text = x.VillaName,
                Value = x.Id.ToString()
            });
            return View(villaNumberCreateVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VillaNumberCreateVM villaNumberCreateVM)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaNumberAPI");
            message.Method = HttpMethod.Post;

            var model = _mapper.Map<VillaNumber>(villaNumberCreateVM.VillaNumber);

            message.Content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage httpResponse = await client.SendAsync(message);
            var apiContent = await httpResponse.Content.ReadAsStringAsync();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Update(int villaNo)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaNumberAPI/" + villaNo);
            message.Method = HttpMethod.Get;

            HttpResponseMessage httpResponse = await client.SendAsync(message);

            var apiContent = await httpResponse.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<APIResponse>(apiContent);
            VillaNumberCreateVM villaNumberCreateVM = new VillaNumberCreateVM();
            var villaNumber = JsonConvert.DeserializeObject<Models.Dto.VillaNumberDTO>(data.Result.ToString());

            villaNumberCreateVM.VillaNumber = villaNumber;


            HttpRequestMessage message1 = new HttpRequestMessage();
            message1.Headers.Add("Accept", "application/json");
            message1.RequestUri = new Uri(villaUrl + "/api/VillaAPI");
            message1.Method = HttpMethod.Get;

            HttpResponseMessage httpResponse1 = await client.SendAsync(message1);

            var apiContent1 = await httpResponse1.Content.ReadAsStringAsync();
            var data1 = JsonConvert.DeserializeObject<APIResponse>(apiContent1);
            var villaList = JsonConvert.DeserializeObject<List<Models.Dto.VillaDTO>>(data1.Result.ToString());

            villaNumberCreateVM.VillaList = villaList.Select(x => new SelectListItem
            {
                Text = x.VillaName,
                Value = x.Id.ToString()
            });

            return View(villaNumberCreateVM);
        } 

        [HttpPost]
        public async Task<IActionResult> Update(VillaNumberCreateVM villaNumberCreateVM)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaNumberAPI/" + villaNumberCreateVM.VillaNumber.VillaNo);
            message.Method = HttpMethod.Put;

            var model = _mapper.Map<VillaNumber>(villaNumberCreateVM.VillaNumber);

            message.Content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage httpResponse = await client.SendAsync(message);
            var apiContent = await httpResponse.Content.ReadAsStringAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int villaNo)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaNumberAPI/" + villaNo);
            message.Method = HttpMethod.Get;

            HttpResponseMessage httpResponse = await client.SendAsync(message);

            var apiContent = await httpResponse.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<APIResponse>(apiContent);
            VillaNumberCreateVM villaNumberCreateVM = new VillaNumberCreateVM();
            var villaNumber = JsonConvert.DeserializeObject<Models.Dto.VillaNumberDTO>(data.Result.ToString());

            villaNumberCreateVM.VillaNumber = villaNumber;


            HttpRequestMessage message1 = new HttpRequestMessage();
            message1.Headers.Add("Accept", "application/json");
            message1.RequestUri = new Uri(villaUrl + "/api/VillaAPI");
            message1.Method = HttpMethod.Get;

            HttpResponseMessage httpResponse1 = await client.SendAsync(message1);

            var apiContent1 = await httpResponse1.Content.ReadAsStringAsync();
            var data1 = JsonConvert.DeserializeObject<APIResponse>(apiContent1);
            var villaList = JsonConvert.DeserializeObject<List<Models.Dto.VillaDTO>>(data1.Result.ToString());

            villaNumberCreateVM.VillaList = villaList.Select(x => new SelectListItem
            {
                Text = x.VillaName,
                Value = x.Id.ToString()
            });

            return View(villaNumberCreateVM);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(VillaNumberCreateVM villaNumberCreateVM)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaNumberAPI/" + villaNumberCreateVM.VillaNumber.VillaNo);
            message.Method = HttpMethod.Delete;

            var model = _mapper.Map<VillaNumber>(villaNumberCreateVM.VillaNumber);

            message.Content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage httpResponse = await client.SendAsync(message);
            var apiContent = await httpResponse.Content.ReadAsStringAsync();

            return RedirectToAction("Index");
        }
    }
}

MagicVilla_Web/Views/VillaNumber/Create.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberCreateVM;

<form asp-action="Create">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa Number</h1>
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaId" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaId" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5"></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a action="Index" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/Delete.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberCreateVM;

<form asp-action="Delete" method="post">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Villa Number</h1>
        <hr />
        <div class="row">

            <input type="hidden" asp-for="VillaNumber.VillaNo" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="VillaNumber.VillaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaId" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <select disabled asp-for="VillaNumber.VillaId" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea disabled asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5"></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="Index" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-success form-control" />
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/Index.cshtml
@model List<MagicVilla_Web.Models.Dto.VillaNumberDTO>

<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa Number List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-outline-primary"><i class="bi bi-plus-circle-fill"></i> Create New Villa Number</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Villa Name</th>
                <th>Villa Number</th>              
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Villa.VillaName</td>
                    <td>@item.VillaNo</td>                   
                    <td>
                        <a asp-controller="VillaNumber" asp-action="Update" asp-route-villaNo="@item.VillaNo" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="VillaNumber" asp-action="Delete" asp-route-villaNo="@item.VillaNo" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MagicVilla_Web/Views/VillaNumber/Update.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberCreateVM;

<form asp-action="Update" method="post">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa Number</h1>
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaId" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaId" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5"></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="Index" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}