MagicVilla_Web/Controllers/AuthController.cs
using AutoMapper;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using System.Text;

namespace MagicVilla_Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IHttpClientFactory _httpClient;
        private readonly IConfiguration _configuration;
        private readonly string villaUrl;
        public AuthController(IHttpClientFactory httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _configuration = configuration;
            villaUrl = _configuration.GetValue<string>("ServiceUrls:VillaAPI");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDTO loginRequestDTO)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/User/login");
            message.Method = HttpMethod.Post;
            message.Content = new StringContent(JsonConvert.SerializeObject(loginRequestDTO), 
                                                                Encoding.UTF8, "application/json");
            HttpResponseMessage httpResponse = await client.SendAsync(message);
            var apiContent = await httpResponse.Content.ReadAsStringAsync();

            var apiResponse = JsonConvert.DeserializeObject<APIResponse>(apiContent);

            if (apiResponse != null && apiResponse.IsSuccess)
            {
                var loginResponse = JsonConvert.DeserializeObject<LoginResponseDTO>(apiResponse.Result.ToString());

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, loginResponse.User.UserName));
                identity.AddClaim(new Claim(ClaimTypes.Role, loginResponse.User.Role));

                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                HttpContext.Session.SetString("SessionToken", loginResponse.Token);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", apiResponse.ErrorMessages.FirstOrDefault());
                return View(loginRequestDTO);
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString("SessionToken", "");
            return RedirectToAction("Index", "Home");
        }

    }
}

MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using MagicVillaAPI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using APIResponse = MagicVilla_Web.Models.APIResponse;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IHttpClientFactory _httpClient;
        private readonly IConfiguration _configuration;
        private readonly string villaUrl;
        private IMapper _mapper;

        public VillaController(IHttpClientFactory httpClient, IConfiguration configuration, IMapper mapper)
        {
            _httpClient = httpClient;
            _configuration = configuration;
            villaUrl = _configuration.GetValue<string>("ServiceUrls:VillaAPI");
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaAPI");
            message.Method = HttpMethod.Get;

            if(HttpContext.Session.GetString("SessionToken") != null)
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", 
                                                    HttpContext.Session.GetString("SessionToken"));
            }

            HttpResponseMessage httpResponse = await client.SendAsync(message);

            var apiContent = await httpResponse.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<APIResponse>(apiContent);
            if (data == null)
            {
                return View(new List<VillaDTO>());
            }
            var villaList = JsonConvert.DeserializeObject<List<VillaDTO>>(data.Result.ToString());
            return View(villaList);
        }
        [HttpGet]
        [Authorize (Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla(VillaDTO villaDTO)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaAPI");
            message.Method = HttpMethod.Post;
            if (HttpContext.Session.GetString("SessionToken") != null)
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",
                                                    HttpContext.Session.GetString("SessionToken"));
            }

            var model = _mapper.Map<Villa>(villaDTO);
       
            message.Content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage httpResponse = await client.SendAsync(message);
            var apiContent = await httpResponse.Content.ReadAsStringAsync();

            TempData["success"] = "Villa added successfully";

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(int villaId)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaAPI/" + villaId);
            message.Method = HttpMethod.Get;
            if (HttpContext.Session.GetString("SessionToken") != null)
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",
                                                    HttpContext.Session.GetString("SessionToken"));
            }

            HttpResponseMessage httpResponse = await client.SendAsync(message);

            var apiContent = await httpResponse.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<APIResponse>(apiContent);
            var villa = JsonConvert.DeserializeObject<VillaDTO>(data.Result.ToString());

            return View(villa);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(VillaDTO villaDTO)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaAPI/" + villaDTO.Id);
            message.Method = HttpMethod.Put;
            if (HttpContext.Session.GetString("SessionToken") != null)
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",
                                                    HttpContext.Session.GetString("SessionToken"));
            }

            var model = _mapper.Map<Villa>(villaDTO);

            message.Content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage httpResponse = await client.SendAsync(message);
            var apiContent = await httpResponse.Content.ReadAsStringAsync();

            TempData["success"] = "Villa updated successfully";

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(int villaId)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaAPI/" + villaId);
            message.Method = HttpMethod.Get;
            if (HttpContext.Session.GetString("SessionToken") != null)
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",
                                                    HttpContext.Session.GetString("SessionToken"));
            }

            HttpResponseMessage httpResponse = await client.SendAsync(message);

            var apiContent = await httpResponse.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<APIResponse>(apiContent);
            var villa = JsonConvert.DeserializeObject<VillaDTO>(data.Result.ToString());

            return View(villa);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(VillaDTO villaDTO)
        {
            var client = _httpClient.CreateClient("MagicAPI");
            HttpRequestMessage message = new HttpRequestMessage();
            message.Headers.Add("Accept", "application/json");
            message.RequestUri = new Uri(villaUrl + "/api/VillaAPI/" + villaDTO.Id);
            message.Method = HttpMethod.Delete;
            if (HttpContext.Session.GetString("SessionToken") != null)
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",
                                                    HttpContext.Session.GetString("SessionToken"));
            }

            var model = _mapper.Map<Villa>(villaDTO);

            message.Content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage httpResponse = await client.SendAsync(message);
            var apiContent = await httpResponse.Content.ReadAsStringAsync();

            TempData["success"] = "Villa deleted successfully";

            return RedirectToAction("Index");
        }
    }
}

MagicVilla_Web/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="Index">Villa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="Index">VillaNumber</a>
                        </li>

                        @if(httpAcc.HttpContext.Session.GetString("SessionToken") != null && 
                               httpAcc.HttpContext.Session.GetString("SessionToken").ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicVilla_Web/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (@TempData["success"] != null) {
<script type="text/javascript">
    Swal.fire({
        position: "top-end",
        icon: "success",
        title: "@TempData["success"]",
        showConfirmButton: false,
        timer: 1500
    });
</script>
}